version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: posgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
